---
- hosts: all
  vars:
    stack_user: "stack"
    stack_home: /home/{{ stack_user }}
    #password: StackPassword
    stack_password: "iPxoMYWOri3eg"
    devstack_dir: "{{ stack_home }}/devstack"
  sudo: yes
  pre_tasks:
    - name: Apt-get Update
      apt: update_cache=yes

    - name: Install Git
      apt: name=git

    - name: Install Pip
      apt: name=python-pip

    - name: Install python-dev
      apt: name=python-dev

    - name: Install python-cffi
      apt: name=python-cffi

    - name: Install python-tox
      apt: name=python-tox

    - name: Install libffi-dev
      apt: name=libffi-dev

    - name: Install libssl-dev
      apt: name=libssl-dev

 
  tasks:
   - name: Create Stack User
     user: name={{ stack_user }}
           password={{ stack_password }}
           comment="Devstack User"
           createhome=yes
           home={{ stack_home }}

   - name: Enable passwordless sudo for stack user
     copy: content="%{{ stack_user }} ALL=(ALL) NOPASSWD:ALL"
           dest=/etc/sudoers.d/{{ stack_user }}
           owner=root
           group=root
           mode=0440

   - name: Clone devstack repo
     sudo_user: stack
     git: repo=https://git.openstack.org/openstack/devstack
          dest={{ devstack_dir }}
